services:
  geofencing:
    build: ./Geofencing-Microservice
    ports:
      - "5001:5001"
    depends_on:
      - carer
    command: gunicorn -w 4 --timeout 120 --preload -b 0.0.0.0:5001 app:app
    volumes:
      - ./Outputs/runCompOutRef.txt:/app/runCompOutRef.txt
      - ./Outputs/runCompOutProp.txt:/app/runCompOutProp.txt
      - ./Outputs/commGeoOutRef.txt:/app/commGeoOutRef.txt
      - ./Outputs/commGeoOutProp.txt:/app/commGeoOutProp.txt

  carer:
    build: ./Carer-Device
    ports:
      - "5002:5002"
    command: gunicorn -w 4 --timeout 120 --preload -b 0.0.0.0:5002 app:app
    volumes:
      - ./Outputs/runDecOutRef.txt:/app/runDecOutRef.txt
      - ./Outputs/runDecOutProp.txt:/app/runDecOutProp.txt
      - ./Outputs/commCarerOutRef.txt:/app/commCarerOutRef.txt
      - ./Outputs/commCarerOutProp.txt:/app/commCarerOutProp.txt