services:
  geofencing:
    build:
      context: ./Geofencing-Microservice
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  keyauthority:
    build:
      context: ./KeyAuthority-Microservice
      dockerfile: Dockerfile
    ports:
      - "5002:5002"